//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NastoleGames.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int GameId { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int Genre { get; set; }
        public string AgeGroup { get; set; }
        public string PlayerCount { get; set; }
        public int StockQuantity { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Genre Genre1 { get; set; }
    }
}
